package it.water.documents.manager.api;

import it.water.core.api.service.BaseEntitySystemApi;
import it.water.documents.manager.model.Document;

import java.io.InputStream;

/**
 * @Generated by Water Generator
 * This interface defines the internally exposed methods for the entity and allows interaction with it bypassing permission system.
 * The main goals of DocumentsManagerSystemApi is to validate the entity and pass it to the persistence layer.
 */
public interface DocumentSystemApi extends BaseEntitySystemApi<Document> {

    /**
     * Retrieve document content
     *
     * @param documentId
     * @return
     */
    InputStream fetchDocumentContent(long documentId);

    /**
     * Retrieve document content by path
     *
     * @param path
     * @return
     */
    InputStream fetchDocumentContentByPath(String path);

    /**
     * Retrieve document content by document uid
     *
     * @param documentUID
     * @return
     */
    InputStream fetchDocumentContentByUID(String documentUID);

}