package it.water.documents.manager.api;

import it.water.core.api.service.BaseEntityApi;
import it.water.documents.manager.model.Document;

import java.io.InputStream;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods for the entity and allows interaction with it through a permission system.
 * All other operations are directly exposed by the basic entity API
 */
public interface DocumentApi extends BaseEntityApi<Document> {

    /**
     * Retrieve document content
     *
     * @param documentId
     * @return
     */
    Document fetchDocumentContent(long documentId);

    /**
     * Retrieve document content by path
     *
     * @param path
     * @return
     */
    Document fetchDocumentContentByPath(String path,String fileName);

    /**
     * Retrieve document content by document uid
     *
     * @param documentUID
     * @return
     */
    Document fetchDocumentContentByUID(String documentUID);

}