package it.water.documents.manager.api;

import it.water.core.api.repository.BaseRepository;
import it.water.documents.manager.model.Folder;

/**
 * @Generated by Water Generator
 * Interface component for DocumentsManager Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 */
public interface FolderRepository extends BaseRepository<Folder> {

}
