package it.water.documents.manager.api;

import it.water.core.api.service.BaseEntityApi;
import it.water.documents.manager.model.Document;
import it.water.documents.manager.model.Folder;

import java.io.InputStream;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods for the entity and allows interaction with it through a permission system.
 * All other operations are directly exposed by the basic entity API
 */
public interface FolderApi extends BaseEntityApi<Folder> {

}