package it.water.documents.manager.api;

import it.water.core.api.service.BaseEntitySystemApi;
import it.water.documents.manager.model.Folder;

/**
 * @Generated by Water Generator
 * This interface defines the internally exposed methods for the entity and allows interaction with it bypassing permission system.
 * The main goals of DocumentsManagerSystemApi is to validate the entity and pass it to the persistence layer.
 */
public interface FolderSystemApi extends BaseEntitySystemApi<Folder> {

}