package it.water.documents.manager.service;

import it.water.core.api.bundle.ApplicationProperties;
import it.water.core.api.permission.SecurityContext;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.api.service.integration.SharedEntityIntegrationClient;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.core.model.exceptions.WaterRuntimeException;
import it.water.core.permission.action.CrudActions;
import it.water.core.permission.annotations.AllowGenericPermissions;
import it.water.core.permission.annotations.AllowPermissions;
import it.water.core.permission.exceptions.UnauthorizedException;
import it.water.documents.manager.api.DocumentApi;
import it.water.documents.manager.api.DocumentSystemApi;
import it.water.documents.manager.model.Document;
import it.water.documents.manager.model.exception.InvalidDocumentUploadException;
import it.water.repository.service.BaseEntityServiceImpl;
import lombok.Getter;
import lombok.Setter;
import org.apache.tika.Tika;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Arrays;
import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * @Generated by Water Generator
 * Service Api Class for DocumentsManager entity.
 */
@FrameworkComponent
public class DocumentServiceImpl extends BaseEntityServiceImpl<Document> implements DocumentApi {

    /**
     * #19: configurable maximum upload size in bytes. Default 10 MiB (10485760).
     * The limit is enforced WITHOUT trusting any client-declared length: the content stream is
     * read up to {@code maxSize + 1} bytes; if even one extra byte is available the upload is
     * rejected, so a malicious client cannot exhaust memory by lying about the length.
     */
    static final String PROP_UPLOAD_MAX_SIZE = "water.documents.upload.max.size";
    static final long DEFAULT_UPLOAD_MAX_SIZE = 10485760L;

    /**
     * #19: configurable comma-separated allow-list of MIME types. The real content type is
     * detected from the file BYTES with Apache Tika ({@code tika-core}), never from the
     * client-declared {@code Content-Type}; an upload whose sniffed type is not in this list
     * is rejected.
     */
    static final String PROP_UPLOAD_ALLOWED_MIME = "water.documents.upload.allowed.mime";
    static final String DEFAULT_UPLOAD_ALLOWED_MIME = "application/pdf,image/png,image/jpeg,text/plain";

    /**
     * Content-type sniffer. {@link Tika} from {@code tika-core} is thread-safe and stateless for
     * {@code detect(byte[])}, so a single shared instance is reused.
     */
    private static final Tika TIKA = new Tika();

    @Inject
    @Getter
    @Setter
    private DocumentSystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    @Inject
    @Setter
    private ApplicationProperties applicationProperties;

    public DocumentServiceImpl() {
        super(Document.class);
    }

    /**
     * #19: validate the uploaded content (size + real MIME type) BEFORE delegating to the
     * permission-checked base save. This is the single Api-layer chokepoint that covers both
     * REST entrypoints ({@code save}/{@code update}) and any direct programmatic caller of
     * {@link DocumentApi}.
     * <p>
     * The {@code @AllowPermissions(SAVE)} is re-declared here on purpose: Java method-level
     * annotations are NOT inherited, so overriding {@code save} would otherwise drop the base
     * permission check. The interceptor fires on this (externally invoked) method; the
     * {@code super.save} call is a plain in-JVM call and does not re-trigger it.
     */
    @Override
    @AllowPermissions(actions = {CrudActions.SAVE})
    public Document save(Document entity) {
        validateAndBoundUploadContent(entity);
        return super.save(entity);
    }

    /**
     * #19: content is optional on update (the multipart {@code file} part is {@code required=false}),
     * so the bound/MIME check only runs when content is actually supplied.
     * <p>
     * {@code @AllowPermissions(UPDATE)} is re-declared for the same reason as {@link #save(Document)}.
     */
    @Override
    @AllowPermissions(actions = {CrudActions.UPDATE})
    public Document update(Document entity) {
        validateAndBoundUploadContent(entity);
        return super.update(entity);
    }

    /**
     * #19 — Centralized upload hardening. When the entity carries upload content:
     * <ol>
     *   <li>read the stream with a hard bound of {@code maxSize + 1} bytes (never {@code readAllBytes()}
     *       unbounded) so an oversize payload cannot exhaust memory;</li>
     *   <li>if more than {@code maxSize} bytes are present, reject with {@link InvalidDocumentUploadException};</li>
     *   <li>detect the REAL content type from the buffered bytes with Tika (not the client Content-Type)
     *       and reject when it is not in the configured allow-list;</li>
     *   <li>replace the entity's content stream with a fresh {@link ByteArrayInputStream} over the
     *       buffered bytes. This also neutralizes any downstream {@code DocumentRepositoryIntegrationClient}
     *       that fully buffers the stream (e.g. an S3 client calling {@code readAllBytes()}): it can only
     *       ever see the already-bounded bytes.</li>
     * </ol>
     */
    private void validateAndBoundUploadContent(Document entity) {
        if (entity == null)
            return;
        InputStream content = entity.getDocumentContentInputStream();
        if (content == null)
            return;

        long maxSize = getMaxUploadSize();
        byte[] bounded = readBounded(content, maxSize);
        if (bounded == null) {
            // more than maxSize bytes were available
            throw new InvalidDocumentUploadException("documentContent", String.valueOf(maxSize),
                    "Uploaded document exceeds the maximum allowed size of " + maxSize + " bytes");
        }

        String detectedMime = TIKA.detect(bounded);
        Set<String> allowed = getAllowedMimeTypes();
        String detectedMimeNormalized = detectedMime == null ? "" : detectedMime.toLowerCase(java.util.Locale.ROOT);
        if (!allowed.contains(detectedMimeNormalized)) {
            throw new InvalidDocumentUploadException("contentType", detectedMime,
                    "Uploaded document MIME type '" + detectedMime + "' is not allowed");
        }

        // hand a fresh, re-readable, already-bounded stream to the storage layer
        entity.setDocumentContentInputStream(new ByteArrayInputStream(bounded));
    }

    /**
     * Reads at most {@code maxSize + 1} bytes from the stream. Returns the buffered bytes when the
     * stream is within the limit, or {@code null} when there is at least one extra byte (i.e. the
     * payload is larger than {@code maxSize}). Never buffers more than {@code maxSize + 1} bytes.
     */
    private byte[] readBounded(InputStream content, long maxSize) {
        try {
            // read up to maxSize+1 so we can detect "over the limit" without trusting any declared length
            byte[] buffer = content.readNBytes((int) Math.min(maxSize + 1, Integer.MAX_VALUE));
            if (buffer.length > maxSize) {
                return null;
            }
            return buffer;
        } catch (IOException e) {
            throw new WaterRuntimeException("Unable to read uploaded document content");
        }
    }

    private long getMaxUploadSize() {
        if (applicationProperties == null)
            return DEFAULT_UPLOAD_MAX_SIZE;
        return Math.max(1L, applicationProperties.getPropertyOrDefault(PROP_UPLOAD_MAX_SIZE, DEFAULT_UPLOAD_MAX_SIZE));
    }

    private Set<String> getAllowedMimeTypes() {
        String raw = DEFAULT_UPLOAD_ALLOWED_MIME;
        if (applicationProperties != null)
            raw = applicationProperties.getPropertyOrDefault(PROP_UPLOAD_ALLOWED_MIME, DEFAULT_UPLOAD_ALLOWED_MIME);
        Set<String> allowed = new LinkedHashSet<>();
        Arrays.stream(raw.split(","))
                .map(String::trim)
                .filter(s -> !s.isEmpty())
                .map(s -> s.toLowerCase(java.util.Locale.ROOT))
                .forEach(allowed::add);
        return allowed;
    }

    @AllowGenericPermissions(actions = CrudActions.FIND)
    @Override
    public Document fetchDocumentContent(long documentId) {
        Document document = systemService.fetchDocumentContent(documentId);
        checkCallerCanAccess(document);
        return document;
    }

    @AllowGenericPermissions(actions = CrudActions.FIND)
    @Override
    public Document fetchDocumentContentByPath(String path, String fileName) {
        // #18: canonicalize/validate before the path reaches the storage backend (traversal hardening).
        validateStorageComponent(path, "path");
        validateStorageComponent(fileName, "fileName");
        Document document = systemService.fetchDocumentContentByPath(path, fileName);
        checkCallerCanAccess(document);
        return document;
    }

    @AllowGenericPermissions(actions = CrudActions.FIND)
    @Override
    public Document fetchDocumentContentByUID(String documentUID) {
        Document document = systemService.fetchDocumentContentByUID(documentUID);
        checkCallerCanAccess(document);
        return document;
    }

    /**
     * #18: per-document instance-level authorization on the RESOLVED document.
     * Generic FIND is not enough — it only proves the caller may read <em>some</em> documents.
     * A caller may read a specific document only if they are admin, the owner, or it is shared with them.
     * Document does not implement {@code OwnedResource} (so the {@code BaseEntityServiceImpl}
     * owned/shared query-scoping does not apply to these fetch-by-X paths), hence the explicit check.
     */
    private void checkCallerCanAccess(Document document) {
        if (document == null)
            return;
        SecurityContext securityContext = this.getRuntime().getSecurityContext();
        if (securityContext == null)
            throw new UnauthorizedException();
        if (securityContext.isAdmin())
            return;
        long loggedEntityId = securityContext.getLoggedEntityId();
        if (loggedEntityId <= 0)
            throw new UnauthorizedException();
        Long ownerUserId = document.getOwnerUserId();
        if (ownerUserId == loggedEntityId)
            return;
        if (isSharedWithCaller(document, loggedEntityId))
            return;
        throw new UnauthorizedException();
    }

    /**
     * #18: a document is accessible if it is among the ids shared with the logged user.
     * Reuses the same {@link SharedEntityIntegrationClient} contract used by the base entity
     * owned/shared scoping (returns the entity ids shared with the given user).
     */
    private boolean isSharedWithCaller(Document document, long loggedEntityId) {
        SharedEntityIntegrationClient sharedEntityIntegrationClient = getSharedEntityIntegrationClient();
        if (sharedEntityIntegrationClient == null)
            return false;
        Collection<Long> sharedIds = sharedEntityIntegrationClient.fetchSharingUsersIds(Document.class.getName(), loggedEntityId);
        return sharedIds != null && sharedIds.contains(document.getId());
    }

    /**
     * #18: reject path/fileName components that could escape the intended storage key
     * (parent traversal, null bytes, Windows separators / drive prefixes). Applied before any storage call.
     * <p>
     * A leading {@code '/'} is intentionally allowed: this module stores documents under rooted paths
     * by convention (e.g. {@code /myPath}, {@code /reports/2024}), so it is part of the storage key, not
     * an escape. The real traversal vector ({@code ..}) is rejected regardless of position. A {@code fileName}
     * must additionally not contain a path separator — it names a single file, never a sub-path.
     */
    private void validateStorageComponent(String value, String fieldName) {
        if (value == null)
            return;
        boolean illegal = value.indexOf('\0') >= 0          // null byte
                || value.contains("..")                      // parent traversal (the real escape vector)
                || value.contains("\\")                      // backslash: Windows separator / traversal
                || value.matches("^[A-Za-z]:.*");            // Windows drive prefix (e.g. C:\...)
        // a fileName names a single file: it must never carry a path separator
        if ("fileName".equals(fieldName))
            illegal = illegal || value.indexOf('/') >= 0;
        if (illegal) {
            throw new WaterRuntimeException("Invalid " + fieldName + ": illegal path component");
        }
    }
}
