package it.water.documents.manager.service;

import it.water.core.api.registry.filter.ComponentFilterBuilder;
import it.water.core.api.repository.query.Query;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.documents.manager.api.DocumentRepository;
import it.water.documents.manager.api.DocumentSystemApi;
import it.water.documents.manager.api.integration.DocumentRepositoryIntegrationClient;
import it.water.documents.manager.model.Document;
import it.water.repository.service.BaseEntitySystemServiceImpl;
import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;



/**
 * @Generated by Water Generator
 * System Service Api Class for DocumentsManager entity.
 *
 * <p><b>SECURITY (#17) — SystemApi is a TRUSTED layer that bypasses ALL permission interceptors.</b>
 * Methods on this class (and any {@code *SystemApi}) run with NO authorization checks. It MUST NEVER be
 * injected directly into a REST controller or any externally-reachable component. REST controllers and
 * other external entry points must depend only on the permission-checked {@code DocumentApi}
 * ({@code *Api}) layer, which enforces ownership/instance-level authorization (see
 * {@code DocumentServiceImpl#checkCallerCanAccess}). Injecting this SystemApi behind a REST endpoint
 * silently disables authorization — exactly the class of defect tracked as #32.
 */
@FrameworkComponent
@Slf4j
public class DocumentSystemServiceImpl extends BaseEntitySystemServiceImpl<Document> implements DocumentSystemApi {
    @Inject
    @Getter
    @Setter
    private DocumentRepository repository;

    @Inject
    @Setter
    private DocumentRepositoryIntegrationClient documentRepositoryIntegrationClient;

    @Inject
    @Setter
    private ComponentFilterBuilder componentFilterBuilder;

    public DocumentSystemServiceImpl() {
        super(Document.class);
    }

    @Override
    public Document fetchDocumentContent(long documentId) {
        Document document = find(documentId);
        fillDocumentEntityWithContent(document);
        return document;
    }

    @Override
    public Document fetchDocumentContentByPath(String path, String fileName) {
        Document d = this.getRepository().findByPath(path, fileName);
        fillDocumentEntityWithContent(d);
        return d;
    }

    @Override
    public Document fetchDocumentContentByUID(String documentUID) {
        Query byUid = getQueryBuilderInstance().field("uid").equalTo(documentUID);
        Document document = find(byUid);
        fillDocumentEntityWithContent(document);
        return document;
    }

    private void fillDocumentEntityWithContent(Document document) {
        document.setDocumentContentInputStream(documentRepositoryIntegrationClient.fetchDocumentContent(document.getFullPath()));
    }
}