package it.water.documents.manager.service;

import it.water.core.api.permission.SecurityContext;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.api.service.integration.SharedEntityIntegrationClient;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.core.model.exceptions.WaterRuntimeException;
import it.water.core.permission.action.CrudActions;
import it.water.core.permission.annotations.AllowGenericPermissions;
import it.water.core.permission.exceptions.UnauthorizedException;
import it.water.documents.manager.api.DocumentApi;
import it.water.documents.manager.api.DocumentSystemApi;
import it.water.documents.manager.model.Document;
import it.water.repository.service.BaseEntityServiceImpl;
import lombok.Getter;
import lombok.Setter;

import java.util.Collection;

/**
 * @Generated by Water Generator
 * Service Api Class for DocumentsManager entity.
 */
@FrameworkComponent
public class DocumentServiceImpl extends BaseEntityServiceImpl<Document> implements DocumentApi {

    @Inject
    @Getter
    @Setter
    private DocumentSystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    public DocumentServiceImpl() {
        super(Document.class);
    }

    @AllowGenericPermissions(actions = CrudActions.FIND)
    @Override
    public Document fetchDocumentContent(long documentId) {
        Document document = systemService.fetchDocumentContent(documentId);
        checkCallerCanAccess(document);
        return document;
    }

    @AllowGenericPermissions(actions = CrudActions.FIND)
    @Override
    public Document fetchDocumentContentByPath(String path, String fileName) {
        // #18: canonicalize/validate before the path reaches the storage backend (traversal hardening).
        validateStorageComponent(path, "path");
        validateStorageComponent(fileName, "fileName");
        Document document = systemService.fetchDocumentContentByPath(path, fileName);
        checkCallerCanAccess(document);
        return document;
    }

    @AllowGenericPermissions(actions = CrudActions.FIND)
    @Override
    public Document fetchDocumentContentByUID(String documentUID) {
        Document document = systemService.fetchDocumentContentByUID(documentUID);
        checkCallerCanAccess(document);
        return document;
    }

    /**
     * #18: per-document instance-level authorization on the RESOLVED document.
     * Generic FIND is not enough — it only proves the caller may read <em>some</em> documents.
     * A caller may read a specific document only if they are admin, the owner, or it is shared with them.
     * Document does not implement {@code OwnedResource} (so the {@code BaseEntityServiceImpl}
     * owned/shared query-scoping does not apply to these fetch-by-X paths), hence the explicit check.
     */
    private void checkCallerCanAccess(Document document) {
        if (document == null)
            return;
        SecurityContext securityContext = this.getRuntime().getSecurityContext();
        if (securityContext == null)
            throw new UnauthorizedException();
        if (securityContext.isAdmin())
            return;
        long loggedEntityId = securityContext.getLoggedEntityId();
        if (loggedEntityId <= 0)
            throw new UnauthorizedException();
        Long ownerUserId = document.getOwnerUserId();
        if (ownerUserId == loggedEntityId)
            return;
        if (isSharedWithCaller(document, loggedEntityId))
            return;
        throw new UnauthorizedException();
    }

    /**
     * #18: a document is accessible if it is among the ids shared with the logged user.
     * Reuses the same {@link SharedEntityIntegrationClient} contract used by the base entity
     * owned/shared scoping (returns the entity ids shared with the given user).
     */
    private boolean isSharedWithCaller(Document document, long loggedEntityId) {
        SharedEntityIntegrationClient sharedEntityIntegrationClient = getSharedEntityIntegrationClient();
        if (sharedEntityIntegrationClient == null)
            return false;
        Collection<Long> sharedIds = sharedEntityIntegrationClient.fetchSharingUsersIds(Document.class.getName(), loggedEntityId);
        return sharedIds != null && sharedIds.contains(document.getId());
    }

    /**
     * #18: reject path/fileName components that could escape the intended storage key
     * (parent traversal, null bytes, Windows separators / drive prefixes). Applied before any storage call.
     * <p>
     * A leading {@code '/'} is intentionally allowed: this module stores documents under rooted paths
     * by convention (e.g. {@code /myPath}, {@code /reports/2024}), so it is part of the storage key, not
     * an escape. The real traversal vector ({@code ..}) is rejected regardless of position. A {@code fileName}
     * must additionally not contain a path separator — it names a single file, never a sub-path.
     */
    private void validateStorageComponent(String value, String fieldName) {
        if (value == null)
            return;
        boolean illegal = value.indexOf('\0') >= 0          // null byte
                || value.contains("..")                      // parent traversal (the real escape vector)
                || value.contains("\\")                      // backslash: Windows separator / traversal
                || value.matches("^[A-Za-z]:.*");            // Windows drive prefix (e.g. C:\...)
        // a fileName names a single file: it must never carry a path separator
        if ("fileName".equals(fieldName))
            illegal = illegal || value.indexOf('/') >= 0;
        if (illegal) {
            throw new WaterRuntimeException("Invalid " + fieldName + ": illegal path component");
        }
    }
}
