package it.water.documents.manager.service;

import it.water.core.api.registry.filter.ComponentFilterBuilder;
import it.water.core.api.repository.query.Query;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.documents.manager.api.DocumentRepository;
import it.water.documents.manager.api.DocumentSystemApi;
import it.water.documents.manager.api.integration.DocumentRepositoryIntegrationClient;
import it.water.documents.manager.model.Document;
import it.water.repository.service.BaseEntitySystemServiceImpl;
import lombok.Getter;
import lombok.Setter;

import java.io.InputStream;


/**
 * @Generated by Water Generator
 * System Service Api Class for DocumentsManager entity.
 */
@FrameworkComponent
public class DocumentSystemServiceImpl extends BaseEntitySystemServiceImpl<Document> implements DocumentSystemApi {
    @Inject
    @Getter
    @Setter
    private DocumentRepository repository;

    @Inject
    @Setter
    private DocumentRepositoryIntegrationClient documentRepositoryIntegrationClient;

    @Inject
    @Setter
    private ComponentFilterBuilder componentFilterBuilder;

    public DocumentSystemServiceImpl() {
        super(Document.class);
    }

    @Override
    public InputStream fetchDocumentContent(long documentId) {
        Document document = find(documentId);
        return documentRepositoryIntegrationClient.fetchDocumentContent(document.getPath());
    }

    @Override
    public InputStream fetchDocumentContentByPath(String path) {
        return documentRepositoryIntegrationClient.fetchDocumentContent(path);
    }

    @Override
    public InputStream fetchDocumentContentByUID(String documentUID) {
        Query byUid = getQueryBuilderInstance().field("uid").equalTo(documentUID);
        Document document = find(byUid);
        return documentRepositoryIntegrationClient.fetchDocumentContent(document.getUid());
    }
}