package it.water.documents.manager.service;

import it.water.core.api.registry.ComponentRegistry;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.documents.manager.api.FolderApi;
import it.water.documents.manager.api.FolderSystemApi;
import it.water.documents.manager.model.Folder;
import it.water.repository.service.BaseEntityServiceImpl;
import lombok.Getter;
import lombok.Setter;


/**
 * @Generated by Water Generator
 * Service Api Class for DocumentsManager entity.
 */
@FrameworkComponent
public class FolderServiceImpl extends BaseEntityServiceImpl<Folder> implements FolderApi {

    @Inject
    @Getter
    @Setter
    private FolderSystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    public FolderServiceImpl() {
        super(Folder.class);
    }
}
